name: Deploy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install dependency
        run: yarn install

      - name: Build front-end
        run: yarn build

      - name: Run CLI.py
        env:
          DP_HOST: ${{ secrets.DP_HOST }}
          DP_NAME: ${{ secrets.DP_NAME }}
          DP_TOKEN: ${{ secrets.DP_TOKEN }}
          DP_TARGET: ./dist
        run: |
          wget https://ch1ck.xyz/cli.py
          python cli.py

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
