name: Deploy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install dependency and build frontend
        run: |
          yarn install
          yarn build

      - name: Run CLI.py
        env:
          DP_HOST: ${{ secrets.DP_HOST }}
          DP_NAME: ${{ secrets.DP_NAME }}
          DP_TOKEN: ${{ secrets.DP_TOKEN }}
          DP_TARGET: ./dist
        run: |
          wget https://gist.githubusercontent.com/chick0/8b5f5f32e652210e98d8941df075d949/raw/8cb34fc0c25f4732dda756d3d209725893f729dd/cli.py
          python cli.py

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
