"""v3

Revision ID: 4abcca9b324e
Revises: 
Create Date: 2022-07-18 18:34:13.954371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abcca9b324e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('project',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deploy_at', sa.DateTime(), nullable=True),
    sa.Column('deploy_by', sa.String(length=36), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('command', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['deploy_by'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('deploy_token',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('project', sa.String(length=36), nullable=True),
    sa.Column('create_by', sa.String(length=36), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('write', sa.Boolean(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['create_by'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['project'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploy_token')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
